baseURL = "https://manual.elklark.com/"
languageCode = "en-us"
title = "Home Assistant Manual"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showBreadCrumbs = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Roku Setup"
  url = "/posts/roku-setup/"
  weight = 2