baseURL = "https://manual.elklark.com/"
languageCode = "en-us"
title = "HA Manual"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[pagination]
  pagerSize = 10

# Enable syntax highlighting
pygmentsUseClasses = true
markup.highlight.noClasses = false

# PaperMod config
[params]
  homeInfoParams = { Title = "Welcome to the HA Manual", Content = "This is your quick-start guide to Home Assistant and related setups." }
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.assets]
  disableFingerprinting = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2