baseURL = "https://manual.elklark.com/"
languageCode = "en-us"
title = "Home Assistant Manual"
theme = "PaperMod"

# Optional but recommended
paginate = 10

[params]
  homeInfoParams = { Title = "Welcome", Content = "This is your Home Assistant Manual." }

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1