baseURL = "https://ha-manual-site.vercel.app/"languageCode = "en-us"
title = "Home Assistant Manual"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1